on:
  issues:
    types: [labeled]

jobs:
  testissues:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: issue comment
        uses: ./