on:
  issues:
    types: [labeled]

jobs:
  greet:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    name: Issue comment
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: issue comment
        uses: ./